on:
  workflow_call:

jobs:
  init:
    name: terragrunt init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform & Terragrunt
      run: |
        brew install tfenv warrensbox/tap/tgswitch
        tfenv install
        tgswitch
    - name: terraform init
      run: terragrunt init
